version: '3.1'
services:

  postgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=restaurante
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
